#!/bin/bash

set -e
# shellcheck disable=SC2034
SH_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
# shellcheck disable=SC2034
ROOT_DIR="$(dirname "$SH_DIR")"

DEV_IMAGE_REGISTRY=etidahouse
DEV_IMAGE_NAME=fake-smtp-server-cpu-issues
DEV_IMAGE_VERSION=1.0.0

echo "$DEV_IMAGE_REGISTRY/$DEV_IMAGE_NAME:$DEV_IMAGE_VERSION"
