#!/bin/bash

set -e
# shellcheck disable=SC2034
SH_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
# shellcheck disable=SC2034
ROOT_DIR="$(dirname "$SH_DIR")"

docker build --tag="$( "$SH_DIR/dev-image-tag" )" \
    -f "$ROOT_DIR/dev.Dockerfile" "$ROOT_DIR"
